### ISSUE TITLE
Need answer please

### ISSUE THREAD

**Issue by SAV-404** [NuclearC/ini-file#2]
first of all i'm so sorry cz this is not the right place to talk about  that but please answer me!?...second of all : is there any possibility to make an extension which can let you play in other agario's protocoles like the 10th one  cz i found from [here](http://web.archive.org/web/20160601000000*/agar.io) all agario's versions... i'm using agarioV72  too..but the updates  come aphter were better,choose from 10 to 18 may 2016 cz it works correctly...any way i hope you'll answer me...thank you so much :)

**Comment by NuclearC** [comment]
yes its pretty possible to make ;)

**Comment by SAV-404** [comment]
for real???....I will be very happy if you show me how...cz i tried it too many times but still not working..please help me

**Comment by SAV-404** [comment]
@NuclearC come one answer please
